-- ==============================================================================
-- DESABILITAR RLS EM TODAS AS TABELAS DE TODAS AS UNIDADES
-- ==============================================================================

-- VOX BH
ALTER TABLE vox_bhn8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_follow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_disparo DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_bh_shared_reports DISABLE ROW LEVEL SECURITY;

-- VOX SP
ALTER TABLE vox_spn8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_follow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_shared_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_sp_disparo DISABLE ROW LEVEL SECURITY;

-- VOX MACEIÓ
ALTER TABLE vox_maceion8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_follow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_shared_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_maceio_disparo DISABLE ROW LEVEL SECURITY;

-- BIA VOX
ALTER TABLE bia_voxn8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_folow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_disparo DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE bia_vox_shared_reports DISABLE ROW LEVEL SECURITY;

-- COLÉGIO PROGRESSO
ALTER TABLE colegio_progresson8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_follow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_disparo DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE colegio_progresso_shared_reports DISABLE ROW LEVEL SECURITY;

-- VOX ES (se existir)
ALTER TABLE vox_esn8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_disparo DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_follow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_shared_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_es_users DISABLE ROW LEVEL SECURITY;

-- VOX RIO (se existir)
ALTER TABLE vox_rion8n_chat_histories DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_agendamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_automation_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_crm_funnel_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_crm_lead_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_disparo DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_follow_normal DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_followup DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_knowbase DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_lembretes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_pausar DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_shared_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE vox_rio_users DISABLE ROW LEVEL SECURITY;

-- TABELAS GLOBAIS
ALTER TABLE followup_schedule DISABLE ROW LEVEL SECURITY;
ALTER TABLE followup_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE followup_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE evolution_api_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE saas_units DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE shared_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE automation_keywords DISABLE ROW LEVEL SECURITY;
ALTER TABLE automation_logs DISABLE ROW LEVEL SECURITY;

-- VERIFICAÇÃO FINAL
SELECT 
    'RLS DESABILITADO EM TODAS AS TABELAS!' as status,
    COUNT(*) as total_tabelas
FROM information_schema.tables
WHERE table_schema = 'public';

-- Testar acesso às tabelas de Vox SP
SELECT 'vox_spn8n_chat_histories' as tabela, COUNT(*) as registros FROM vox_spn8n_chat_histories
UNION ALL
SELECT 'vox_sp_pausar', COUNT(*) FROM vox_sp_pausar
UNION ALL
SELECT 'vox_sp_agendamentos', COUNT(*) FROM vox_sp_agendamentos;
